In [187]:
import os
import requests
import pandas as pd
import time

In [188]:
my_dict ={"User-Agent":"Prudhvi Raj vicky.prudhvi@gmail.com"}
URL='https://www.sec.gov/files/company_tickers.json'

In [14]:
response= requests.get(URL,headers=my_dict)

In [15]:
response.status_code

200

In [19]:
data =response.json()

In [24]:
list(data.items())[:3]

[('0', {'cik_str': 1045810, 'ticker': 'NVDA', 'title': 'NVIDIA CORP'}),
 ('1', {'cik_str': 320193, 'ticker': 'AAPL', 'title': 'Apple Inc.'}),
 ('2', {'cik_str': 1652044, 'ticker': 'GOOGL', 'title': 'Alphabet Inc.'})]

In [34]:
data_df= pd.DataFrame(data.values())

In [37]:
data_df.head()

   cik_str ticker           title
0  1045810   NVDA     NVIDIA CORP
1   320193   AAPL      Apple Inc.
2  1652044  GOOGL   Alphabet Inc.
3   789019   MSFT  MICROSOFT CORP
4  1018724   AMZN  AMAZON COM INC

In [43]:
my_tickers=["NVDA","AAPL","GOOGL","MSFT","AMZN","T","COST","TSLA","UNH","CF"]

In [48]:
companies=data_df[data_df["ticker"].isin(my_tickers)].reset_index(drop=True)
companies

   cik_str ticker                         title
0  1045810   NVDA                   NVIDIA CORP
1   320193   AAPL                    Apple Inc.
2  1652044  GOOGL                 Alphabet Inc.
3   789019   MSFT                MICROSOFT CORP
4  1018724   AMZN                AMAZON COM INC
5  1318605   TSLA                   Tesla, Inc.
6   909832   COST    COSTCO WHOLESALE CORP /NEW
7   731766    UNH        UNITEDHEALTH GROUP INC
8   732717      T                     AT&T INC.
9  1324404     CF  CF Industries Holdings, Inc.

In [51]:
companies["cik"]=companies["cik_str"].astype(str).str.zfill(10)
companies

   cik_str ticker                         title         cik
0  1045810   NVDA                   NVIDIA CORP  0001045810
1   320193   AAPL                    Apple Inc.  0000320193
2  1652044  GOOGL                 Alphabet Inc.  0001652044
3   789019   MSFT                MICROSOFT CORP  0000789019
4  1018724   AMZN                AMAZON COM INC  0001018724
5  1318605   TSLA                   Tesla, Inc.  0001318605
6   909832   COST    COSTCO WHOLESALE CORP /NEW  0000909832
7   731766    UNH        UNITEDHEALTH GROUP INC  0000731766
8   732717      T                     AT&T INC.  0000732717
9  1324404     CF  CF Industries Holdings, Inc.  0001324404

In [55]:
companies.to_csv("companies.csv",index=False)

In [71]:
apple_cik=companies[companies["ticker"]=="AAPL"].iloc[0]["cik"]
apple_cik

'0000320193'

In [84]:
URL=f"https://data.sec.gov/submissions/CIK{apple_cik}.json"
URL

'https://data.sec.gov/submissions/CIK0000320193.json'

In [92]:
response=requests.get(URL,headers=my_dict)
response.status_code

200

In [93]:
apple=response.json()

In [78]:
apple.keys()

dict_keys(['cik', 'entityType', 'sic', 'sicDescription', 'ownerOrg', 'insiderTransactionForOwnerExists', 'insiderTransactionForIssuerExists', 'name', 'tickers', 'exchanges', 'ein', 'lei', 'description', 'website', 'investorWebsite', 'category', 'fiscalYearEnd', 'stateOfIncorporation', 'stateOfIncorporationDescription', 'addresses', 'phone', 'flags', 'formerNames', 'filings'])

In [97]:
apple_filings=pd.DataFrame(apple["filings"]["recent"])
apple_filings.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,core_type,size,isXBRL,isInlineXBRL,isXBRLNumeric,primaryDocument,primaryDocDescription
0,0001140361-26-039158,2026-10-08,2026-10-06,2026-10-09T02:30:32.000Z,,4,,,,4,4822,0,0,0.0,xslF345X06/form4.xml,FORM 4
1,0001140361-26-038674,2026-10-05,2026-10-01,2026-10-06T02:42:45.000Z,,4,,,,4,20288,0,0,0.0,xslF345X06/form4.xml,FORM 4
2,0001140361-26-038672,2026-10-05,2026-10-01,2026-10-06T02:39:10.000Z,,4,,,,4,14780,0,0,0.0,xslF345X06/form4.xml,FORM 4
3,0001140361-26-038669,2026-10-05,2026-10-01,2026-10-06T02:35:24.000Z,,4,,,,4,18851,0,0,0.0,xslF345X06/form4.xml,FORM 4
4,0001140361-26-038667,2026-10-05,2026-10-01,2026-10-06T02:32:06.000Z,,4,,,,4,11578,0,0,0.0,xslF345X06/form4.xml,FORM 4

In [99]:
apple_filings.shape

(1001, 16)

In [100]:
apple_filings["form"].value_counts()

form
4                 598
8-K               102
144                49
424B2              42
10-Q               33
PX14A6G            27
SC 13G/A           22
FWP                21
3                  12
DEFA14A            12
SD                 11
DEF 14A            11
10-K               11
NO ACT              7
25-NSE              4
S-8                 4
S-3ASR              4
8-A12B              4
UPLOAD              3
CORRESP             3
S-8 POS             3
8-K/A               2
SCHEDULE 13G/A      2
IRANNOTICE          2
CERT                2
CERTNYS             2
SCHEDULE 13G        1
144/A               1
5                   1
4/A                 1
PX14A6N             1
3/A                 1
25                  1
SC 13G              1
Name: count, dtype: int64

In [104]:
apple_8k=apple_filings[apple_filings["form"]=="8-K"]
apple_8k.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,core_type,size,isXBRL,isInlineXBRL,isXBRLNumeric,primaryDocument,primaryDocDescription
28,0000320193-26-000018,2026-07-30,2026-07-30,2026-07-31T00:30:28.000Z,34,8-K,001-36743,261223821,"2.02,9.01",XBRL,417360,1,1,0.0,aapl-20260730.htm,8-K
39,0000320193-26-000011,2026-04-30,2026-04-30,2026-05-01T00:30:41.000Z,34,8-K,001-36743,26926130,"2.02,9.01",XBRL,412047,1,1,0.0,aapl-20260430.htm,8-K
43,0001140361-26-015711,2026-04-20,2026-04-17,2026-04-21T01:29:51.000Z,34,8-K,001-36743,26876142,5.02,XBRL,239761,1,1,0.0,ef20071035_8k.htm,8-K
61,0001140361-26-006577,2026-02-24,2026-02-24,2026-02-25T02:55:58.000Z,34,8-K,001-36743,26672649,"5.07,9.01",XBRL,415164,1,1,NaN,ef20060722_8k.htm,8-K
70,0000320193-26-000005,2026-01-29,2026-01-29,2026-01-30T02:30:33.000Z,34,8-K,001-36743,26578546,"2.02,9.01",XBRL,384366,1,1,NaN,aapl-20260129.htm,8-K

In [106]:
apple_8k["items"].value_counts()

items
2.02,9.01         45
8.01,9.01         23
5.02              13
5.07               7
5.03,9.01          4
7.01,9.01          3
5.07,9.01          2
5.02,5.03,9.01     2
5.02,5.07,9.01     2
7.01               1
Name: count, dtype: int64

In [131]:
apple_earnings=apple_8k[apple_8k["items"].str.contains("2.02",regex=False)]
apple_earnings=apple_earnings[["accessionNumber","filingDate", "reportDate", "form", "items", "primaryDocument"]].reset_index(drop=True)
apple_earnings

,accessionNumber,filingDate,reportDate,form,items,primaryDocument
0,0000320193-26-000018,2026-07-30,2026-07-30,8-K,"2.02,9.01",aapl-20260730.htm
1,0000320193-26-000011,2026-04-30,2026-04-30,8-K,"2.02,9.01",aapl-20260430.htm
2,0000320193-26-000005,2026-01-29,2026-01-29,8-K,"2.02,9.01",aapl-20260129.htm
3,0000320193-25-000077,2025-10-30,2025-10-30,8-K,"2.02,9.01",aapl-20251030.htm
4,0000320193-25-000071,2025-07-31,2025-07-31,8-K,"2.02,9.01",aapl-20250731.htm
5,0000320193-25-000055,2025-05-01,2025-05-01,8-K,"2.02,9.01",aapl-20250501.htm
6,0000320193-25-000007,2025-01-30,2025-01-30,8-K,"2.02,9.01",aapl-20250130.htm
7,0000320193-24-000120,2024-10-31,2024-10-31,8-K,"2.02,9.01",aapl-20241031.htm
8,0000320193-24-000080,2024-08-01,2024-08-01,8-K,"2.02,9.01",aapl-20240801.htm
9,0000320193-24-000067,2024-05-02,2024-05-02,8-K,"2.02,9.01",aapl-20240502.htm
10,0000320193-24-000005,2024-02-01,2024-02-01,8-K,"2.02,9.01",aapl-20240201.htm
11,0000320193-23-000104,2023-11-02,2023-11-02,8-K,"2.02,9.01",aapl-20231102.htm
12,0000320193-23-000075,2023-08-03,2023-08-03,8-K,"2.02,9.01",aapl-20230803.htm
13,0000320193-23-000063,2023-05-04,2023-05-04,8-K,"2.02,9.01",aapl-20230504.htm
14,0000320193-23-000005,2023-02-02,2023-02-02,8-K,"2.02,9.01",aapl-20230202.htm
15,0000320193-22-000107,2022-10-27,2022-10-27,8-K,"2.02,9.01",aapl-20221027.htm
16,0000320193-22-000069,2022-07-28,2022-07-28,8-K,"2.02,9.01",aapl-20220728.htm
17,0000320193-22-000058,2022-04-28,2022-04-28,8-K,"2.02,9.01",aapl-20220428.htm
18,0000320193-22-000006,2022-01-27,2022-01-27,8-K,"2.02,9.01",aapl-20220127.htm
19,0000320193-21-000104,2021-10-28,2021-10-28,8-K,"2.02,9.01",aapl-20211028.htm
20,0000320193-21-000063,2021-07-27,2021-07-27,8-K,"2.02,9.01",aapl-20210727.htm
21,0000320193-21-000055,2021-04-28,2021-04-28,8-K,"2.02,9.01",aapl-20210428.htm
22,0000320193-21-000009,2021-01-27,2021-01-27,8-K,"2.02,9.01",aapl-20210127.htm
23,0000320193-20-000094,2020-10-29,2020-10-29,8-K,"2.02,9.01",aapl-20201029.htm
24,0000320193-20-000060,2020-07-30,2020-07-30,8-K,"2.02,9.01",aapl-20200730.htm
25,0000320193-20-000050,2020-04-30,2020-04-30,8-K,"2.02,9.01",a8-kq220203282020.htm
26,0000320193-20-000008,2020-01-28,2020-01-28,8-K,"2.02,9.01",a8-kq1202012282019.htm
27,0000320193-19-000117,2019-10-30,2019-10-30,8-K,"2.02,9.01",a8-kq420199282019.htm
28,0000320193-19-000073,2019-07-30,2019-07-30,8-K,"2.02,9.01",a8-kq320196292019.htm
29,0000320193-19-000063,2019-04-30,2019-04-30,8-K,"2.02,9.01",a8-kq220193302019.htm
30,0000320193-19-000007,2019-01-29,2019-01-29,8-K,"2.02,9.01",a8-kq1201912292018.htm
31,0000320193-19-000002,2019-01-02,2019-01-02,8-K,"2.02,9.01",a8-kjanuary2019122019.htm
32,0000320193-18-000142,2018-11-01,2018-11-01,8-K,"2.02,9.01",a8-kq420189292018.htm
33,0000320193-18-000098,2018-07-31,2018-07-31,8-K,"2.02,9.01",a8-kq320186302018.htm
34,0000320193-18-000067,2018-05-01,2018-05-01,8-K,"2.02,9.01",a8-kq220183312018.htm
35,0000320193-18-000005,2018-02-01,2018-02-01,8-K,"2.02,9.01",a8-kq1201812302017.htm
36,0000320193-17-000067,2017-11-02,2017-11-02,8-K,"2.02,9.01",a8-kq420179302017.htm
37,0000320193-17-000006,2017-08-01,2017-08-01,8-K,"2.02,9.01",a8-kq32017712017.htm
38,0001628280-17-004663,2017-05-02,2017-05-02,8-K,"2.02,9.01",a8-kq22017412017.htm
39,0001628280-17-000663,2017-01-31,2017-01-31,8-K,"2.02,9.01",a8-kq1201712312016.htm
40,0001628280-16-020258,2016-10-25,2016-10-25,8-K,"2.02,9.01",a8-kq420169242016.htm
41,0001628280-16-017762,2016-07-26,2016-07-26,8-K,"2.02,9.01",a8-kq320166252016.htm
42,0001193125-16-556520,2016-04-26,2016-04-26,8-K,"2.02,9.01",d325078d8k.htm
43,0001193125-16-438421,2016-01-26,2016-01-26,8-K,"2.02,9.01",d22806d8k.htm
44,0001193125-15-354756,2015-10-27,2015-10-27,8-K,"2.02,9.01",d74332d8k.htm

In [123]:
apple_earnings.shape

(45, 6)

In [126]:
print(apple_earnings["filingDate"].min())
print(apple_earnings["filingDate"].max())

2015-10-27
2026-07-30

In [193]:
apple_cik_num=companies[companies["ticker"]=="AAPL"].iloc[0]["cik_str"]
apple_cik_num

np.int64(320193)

In [220]:
def download_press_release(cik_num,accession_num ,ticker):
    folder_path = f"data/raw/{ticker}"    
    accession = accession_num.replace("-", "")
    file_path = f"{folder_path}/{accession}.htm"
    
    if os.path.exists(file_path):
        print( "skipped")
        return
    # Get the list of files in this filing's folder
    folder_url = f"https://www.sec.gov/Archives/edgar/data/{cik_num}/{accession}/index.json"
    # print(f"https://www.sec.gov/Archives/edgar/data/{cik_num}/{accession}")
    folder_response = requests.get(folder_url, headers=my_dict)
    time.sleep(0.2)
    if folder_response.status_code != 200:
        print(f"Failed folder {accession_num}: {folder_response.status_code}")
        return

    folder_df = pd.DataFrame(folder_response.json()["directory"]["item"])

    # Find the exhibit 99 file (the press release)
    matches = folder_df[folder_df["name"].str.contains("ex99|exhibit99",  case=False)]
    if matches.empty:
        print(f"No ex99 file in {accession_num}")
        return
    press_release_name = matches["name"].iloc[0]

    # Download the press release (uses cik_num, not apple_cik_num)
    file_url = f"https://www.sec.gov/Archives/edgar/data/{cik_num}/{accession}/{press_release_name}"
    file_response = requests.get(file_url, headers=my_dict)
    time.sleep(0.2)
    if file_response.status_code != 200:
        print(f"Failed file {accession_num}: {file_response.status_code}")
        return

    # Save the raw HTML
    
    os.makedirs(folder_path, exist_ok=True)
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(file_response.text)

    print(f"Saved {file_path}")

In [221]:
download_press_release(apple_cik_num,"0000320193-26-000011","AAPL")

Saved data/raw/AAPL/000032019326000011.htm

In [230]:
def get_earnings_filings(cik,ticker):
    URL=f"https://data.sec.gov/submissions/CIK{cik}.json"
    company_response=requests.get(URL,headers=my_dict)
    time.sleep(0.2)
    if company_response.status_code !=200:
         print(f"Failed folder {cik}: {compang_response.status_code}")
         return
    company=company_response.json()
    company_filings=pd.DataFrame(company["filings"]["recent"])
    company_8k=company_filings[company_filings["form"]=="8-K"]
    company_earnings=company_8k[company_8k["items"].str.contains("2.02",regex=False)]
    company_earnings=company_earnings[["accessionNumber","filingDate", "reportDate", "form", "items", "primaryDocument"]].reset_index(drop=True)    
    for acc  in company_earnings["accessionNumber"]:
        download_press_release(cik,acc ,ticker)

In [234]:
for cik, ticker in zip(companies["cik"],companies["ticker"]):
    get_earnings_filings(cik, ticker)

No ex99 file in 0001045810-26-000073
No ex99 file in 0001045810-26-000051
No ex99 file in 0001045810-26-000019
No ex99 file in 0001045810-25-000228
No ex99 file in 0001045810-25-000207
No ex99 file in 0001045810-25-000115
No ex99 file in 0001045810-25-000021
No ex99 file in 0001045810-24-000315
No ex99 file in 0001045810-24-000262
No ex99 file in 0001045810-24-000113
No ex99 file in 0001045810-24-000028
No ex99 file in 0001045810-23-000225
No ex99 file in 0001045810-23-000171
No ex99 file in 0001045810-23-000087
No ex99 file in 0001045810-23-000014
No ex99 file in 0001045810-22-000163
No ex99 file in 0001045810-22-000136
No ex99 file in 0001045810-22-000133
No ex99 file in 0001045810-22-000073
No ex99 file in 0001045810-22-000008
No ex99 file in 0001045810-21-000160
No ex99 file in 0001045810-21-000128
No ex99 file in 0001045810-21-000063
No ex99 file in 0001045810-21-000007
No ex99 file in 0001045810-20-000187
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
skipped
Saved data/raw/GOOGL/000165204426000066.htm
Saved data/raw/GOOGL/000165204426000043.htm
Saved data/raw/GOOGL/000165204426000012.htm
Saved data/raw/GOOGL/000165204425000087.htm
Saved data/raw/GOOGL/000165204425000056.htm
Saved data/raw/GOOGL/000165204425000040.htm
Saved data/raw/GOOGL/000165204425000010.htm
Saved data/raw/GOOGL/000165204424000115.htm
Saved data/raw/GOOGL/000165204424000076.htm
Saved data/raw/GOOGL/000165204424000047.htm
Saved data/raw/GOOGL/000165204424000014.htm
Saved data/raw/GOOGL/000165204423000088.htm
Saved data/raw/GOOGL/000165204423000067.htm
Saved data/raw/MSFT/000119312526323632.htm
Saved data/raw/MSFT/000119312526191457.htm
Saved data/raw/MSFT/000119312526027198.htm
Saved data/raw/MSFT/000119312525256310.htm
Saved data/raw/MSFT/000095017025100226.htm
Saved data/raw/MSFT/000095017025061032.htm
Saved data/raw/MSFT/000095017025010484.htm
Saved data/raw/MSFT/000095017024118955.htm
Saved data/raw/MSFT/000095017024087835.htm
Saved data/raw/MSFT/000095017024048268.htm
Saved data/raw/MSFT/000095017024008809.htm
Saved data/raw/MSFT/000095017023054848.htm
Saved data/raw/MSFT/000095017023034400.htm
Saved data/raw/MSFT/000119312523115280.htm
Saved data/raw/MSFT/000119312523014230.htm
Saved data/raw/MSFT/000119312522268356.htm
Saved data/raw/MSFT/000119312522202034.htm
Saved data/raw/MSFT/000119312522120207.htm
Saved data/raw/MSFT/000119312522017041.htm
Saved data/raw/MSFT/000119312521307941.htm
Saved data/raw/MSFT/000119312521225746.htm
Saved data/raw/MSFT/000119312521134213.htm
Saved data/raw/MSFT/000119312521017683.htm
Saved data/raw/MSFT/000119312520278410.htm
Saved data/raw/AMZN/000101872426000024.htm
Saved data/raw/AMZN/000101872426000012.htm
Saved data/raw/AMZN/000101872426000002.htm
Saved data/raw/AMZN/000101872425000121.htm
Saved data/raw/AMZN/000101872425000084.htm
Saved data/raw/AMZN/000101872425000034.htm
Saved data/raw/AMZN/000101872425000002.htm
Saved data/raw/AMZN/000101872424000158.htm
Saved data/raw/AMZN/000101872424000128.htm
Saved data/raw/AMZN/000101872424000081.htm
Saved data/raw/AMZN/000101872424000006.htm
Saved data/raw/AMZN/000101872423000016.htm
Saved data/raw/AMZN/000101872423000010.htm
Saved data/raw/AMZN/000101872423000006.htm
Saved data/raw/AMZN/000101872423000002.htm
Saved data/raw/AMZN/000101872422000021.htm
Saved data/raw/AMZN/000101872422000017.htm
Saved data/raw/AMZN/000101872422000011.htm
Saved data/raw/AMZN/000101872422000002.htm
Saved data/raw/AMZN/000101872421000026.htm
Saved data/raw/AMZN/000101872421000018.htm
Saved data/raw/AMZN/000101872421000008.htm
Saved data/raw/AMZN/000101872421000002.htm
Saved data/raw/AMZN/000101872420000028.htm
Saved data/raw/TSLA/000162828026064366.htm
Saved data/raw/TSLA/000162828026049213.htm
Saved data/raw/TSLA/000162828026046717.htm
Saved data/raw/TSLA/000162828026026551.htm
Saved data/raw/TSLA/000162828026022956.htm
Saved data/raw/TSLA/000162828026003837.htm
Saved data/raw/TSLA/000162828026000016.htm
Saved data/raw/TSLA/000162828025045861.htm
Saved data/raw/TSLA/000162828025043530.htm
Saved data/raw/TSLA/000162828025035738.htm
Saved data/raw/TSLA/000162828025033842.htm
No ex99 file in 0001628280-25-018851
Saved data/raw/TSLA/000162828025016070.htm
Saved data/raw/TSLA/000162828025002993.htm
Saved data/raw/TSLA/000162828025000007.htm
No ex99 file in 0001628280-24-043432
Saved data/raw/TSLA/000162828024041816.htm
No ex99 file in 0001628280-24-032603
Saved data/raw/TSLA/000162828024030714.htm
Saved data/raw/TSLA/000095017024046895.htm
Saved data/raw/TSLA/000095017024040274.htm
Saved data/raw/TSLA/000095017024007073.htm
Saved data/raw/TSLA/000095017024000282.htm
Saved data/raw/TSLA/000162828023034588.htm
Saved data/raw/TSLA/000095017023050938.htm
Saved data/raw/TSLA/000095017023033544.htm
Saved data/raw/TSLA/000095017023031241.htm
Saved data/raw/TSLA/000156459023005959.htm
Saved data/raw/TSLA/000156459023005126.htm
Saved data/raw/TSLA/000156459023000799.htm
Saved data/raw/TSLA/000156459023000002.htm
Saved data/raw/TSLA/000156459022034639.htm
Saved data/raw/TSLA/000156459022033053.htm
Saved data/raw/TSLA/000156459022026048.htm
Saved data/raw/TSLA/000156459022025153.htm
Saved data/raw/TSLA/000156459022014917.htm
Saved data/raw/TSLA/000156459022013264.htm
Saved data/raw/TSLA/000156459022002476.htm
Saved data/raw/TSLA/000156459022000009.htm
Saved data/raw/TSLA/000156459021051307.htm
Saved data/raw/TSLA/000156459021049874.htm
Saved data/raw/TSLA/000156459021037953.htm
Saved data/raw/TSLA/000095017021000423.htm
Saved data/raw/TSLA/000156459021020558.htm
Saved data/raw/TSLA/000156459021017443.htm
Saved data/raw/TSLA/000156459021002645.htm
Saved data/raw/TSLA/000156459021000008.htm
Saved data/raw/TSLA/000156459020047108.htm
Saved data/raw/TSLA/000156459020045592.htm
Saved data/raw/TSLA/000156459020033069.htm
Saved data/raw/TSLA/000156459020031568.htm
Saved data/raw/TSLA/000156459020019776.htm
Saved data/raw/TSLA/000156459020014992.htm
Saved data/raw/TSLA/000156459020002489.htm
Saved data/raw/TSLA/000156459020000161.htm
Saved data/raw/TSLA/000156459019037581.htm
Saved data/raw/TSLA/000156459019036274.htm
Saved data/raw/TSLA/000156459019025855.htm
Saved data/raw/TSLA/000156459019024414.htm
Saved data/raw/TSLA/000156459019012758.htm
Saved data/raw/TSLA/000156459019010743.htm
Saved data/raw/TSLA/000156459019001399.htm
Saved data/raw/TSLA/000156459019000740.htm
Saved data/raw/TSLA/000156459019000013.htm
Saved data/raw/TSLA/000156459018024902.htm
Saved data/raw/TSLA/000156459018023815.htm
Saved data/raw/TSLA/000156459018023716.htm
Saved data/raw/TSLA/000156459018018490.htm
Saved data/raw/TSLA/000156459018016465.htm
Saved data/raw/COST/000090983226000084.htm
Saved data/raw/COST/000090983226000046.htm
Saved data/raw/COST/000090983226000025.htm
Saved data/raw/COST/000090983225000164.htm
Saved data/raw/COST/000090983225000093.htm
Saved data/raw/COST/000090983225000031.htm
Saved data/raw/COST/000090983225000012.htm
Saved data/raw/COST/000090983224000075.htm
Saved data/raw/COST/000090983224000043.htm
Saved data/raw/COST/000090983224000026.htm
Saved data/raw/COST/000090983224000012.htm
Saved data/raw/COST/000090983223000062.htm
Saved data/raw/COST/000090983223000038.htm
Saved data/raw/COST/000090983223000025.htm
Saved data/raw/COST/000090983223000010.htm
Saved data/raw/COST/000090983222000029.htm
Saved data/raw/COST/000119312522249988.htm
Saved data/raw/COST/000119312522161034.htm
Saved data/raw/COST/000119312522065629.htm
Saved data/raw/COST/000119312521352764.htm
Saved data/raw/COST/000119312521280728.htm
Saved data/raw/COST/000119312521175491.htm
Saved data/raw/COST/000119312521069673.htm
Saved data/raw/COST/000119312520314970.htm
Saved data/raw/COST/000119312520253502.htm
Saved data/raw/COST/000119312520154276.htm
Saved data/raw/COST/000119312520063247.htm
Saved data/raw/COST/000119312519312824.htm
Saved data/raw/COST/000119312519261698.htm
Saved data/raw/COST/000119312519161475.htm
Saved data/raw/COST/000119312519067406.htm
Saved data/raw/COST/000119312518348921.htm
Saved data/raw/COST/000119312518293414.htm
Saved data/raw/COST/000119312518180670.htm
Saved data/raw/COST/000119312518073668.htm
Saved data/raw/COST/000119312517369704.htm
Saved data/raw/COST/000119312517304742.htm
Saved data/raw/COST/000119312517184018.htm
Saved data/raw/COST/000119312517069544.htm
Saved data/raw/COST/000119312516787613.htm
No ex99 file in 0000731766-26-000255
No ex99 file in 0000731766-26-000191
No ex99 file in 0000731766-26-000121
No ex99 file in 0000731766-26-000025
Saved data/raw/UNH/000073176625000301.htm
Saved data/raw/UNH/000073176625000228.htm
Saved data/raw/UNH/000073176625000123.htm
Saved data/raw/UNH/000073176625000022.htm
Saved data/raw/UNH/000073176624000320.htm
Saved data/raw/UNH/000073176624000242.htm
Saved data/raw/UNH/000073176624000146.htm
Saved data/raw/UNH/000073176624000023.htm
Saved data/raw/UNH/000073176623000058.htm
Saved data/raw/UNH/000073176623000049.htm
Saved data/raw/UNH/000073176623000026.htm
Saved data/raw/UNH/000073176623000003.htm
Saved data/raw/UNH/000073176622000041.htm
Saved data/raw/UNH/000073176622000033.htm
Saved data/raw/UNH/000073176622000016.htm
Saved data/raw/UNH/000073176622000004.htm
Saved data/raw/UNH/000073176621000040.htm
Saved data/raw/UNH/000073176621000033.htm
Saved data/raw/UNH/000073176621000018.htm
Saved data/raw/T/000073271726000294.htm
Saved data/raw/T/000073271726000203.htm
Saved data/raw/T/000073271726000047.htm
Saved data/raw/T/000073271725000163.htm
Saved data/raw/T/000073271725000076.htm
Saved data/raw/T/000073271725000020.htm
Saved data/raw/T/000073271725000007.htm
Saved data/raw/T/000073271724000056.htm
Saved data/raw/T/000073271724000050.htm
Saved data/raw/T/000073271724000018.htm
Saved data/raw/T/000073271724000006.htm
Saved data/raw/T/000073271723000054.htm
Saved data/raw/T/000073271723000043.htm
Saved data/raw/T/000073271723000019.htm
Saved data/raw/T/000073271723000007.htm
Saved data/raw/T/000073271722000099.htm
Saved data/raw/T/000073271722000080.htm
Saved data/raw/CF/000110465926091275.htm
Saved data/raw/CF/000132440426000017.htm
Saved data/raw/CF/000110465926056338.htm
Saved data/raw/CF/000132440426000011.htm
Saved data/raw/CF/000110465926017110.htm
Saved data/raw/CF/000132440426000003.htm
Saved data/raw/CF/000110465925107103.htm
Saved data/raw/CF/000132440425000028.htm
Saved data/raw/CF/000110465925074767.htm
Saved data/raw/CF/000132440425000022.htm
Saved data/raw/CF/000110465925045606.htm
Saved data/raw/CF/000132440425000013.htm
Saved data/raw/CF/000110465925015219.htm
Saved data/raw/CF/000132440425000004.htm
Saved data/raw/CF/000110465924112673.htm
Saved data/raw/CF/000132440424000024.htm
Saved data/raw/CF/000110465924086801.htm
Saved data/raw/CF/000132440424000018.htm
Saved data/raw/CF/000110465924055837.htm
Saved data/raw/CF/000132440424000012.htm
Saved data/raw/CF/000110465924024069.htm
Saved data/raw/CF/000132440424000003.htm
Saved data/raw/CF/000110465923113430.htm
Saved data/raw/CF/000132440423000022.htm
Saved data/raw/CF/000110465923086877.htm
Saved data/raw/CF/000132440423000017.htm
Saved data/raw/CF/000110465923054477.htm
Saved data/raw/CF/000132440423000010.htm
Saved data/raw/CF/000110465923022431.htm
Saved data/raw/CF/000132440423000003.htm
No ex99 file in 0001104659-22-114033
Saved data/raw/CF/000132440422000026.htm
Saved data/raw/CF/000110465922084736.htm
Saved data/raw/CF/000132440422000020.htm
Saved data/raw/CF/000110465922055931.htm
Saved data/raw/CF/000132440422000014.htm
Saved data/raw/CF/000110465922024015.htm
Saved data/raw/CF/000132440422000004.htm
Saved data/raw/CF/000110465921133868.htm
Saved data/raw/CF/000132440421000030.htm
Saved data/raw/CF/000110465921102325.htm
Saved data/raw/CF/000132440421000020.htm
Saved data/raw/CF/000110465921061883.htm
Saved data/raw/CF/000132440421000011.htm
Saved data/raw/CF/000110465921024963.htm
Saved data/raw/CF/000132440421000004.htm
Saved data/raw/CF/000110465920121424.htm
Saved data/raw/CF/000132440420000023.htm
Saved data/raw/CF/000110465920090923.htm
Saved data/raw/CF/000132440420000017.htm
Saved data/raw/CF/000110465920057641.htm
Saved data/raw/CF/000132440420000010.htm
Saved data/raw/CF/000110465920019476.htm
Saved data/raw/CF/000132440420000002.htm
Saved data/raw/CF/000110465919057897.htm
Saved data/raw/CF/000132440419000021.htm
Saved data/raw/CF/000110465919043009.htm
Saved data/raw/CF/000132440419000016.htm
Saved data/raw/CF/000110465919026136.htm
Saved data/raw/CF/000132440419000009.htm
Saved data/raw/CF/000110465919007986.htm
Saved data/raw/CF/000132440419000003.htm
Saved data/raw/CF/000110465918065148.htm
Saved data/raw/CF/000132440418000024.htm
Saved data/raw/CF/000110465918048811.htm
Saved data/raw/CF/000132440418000017.htm
Saved data/raw/CF/000110465918029887.htm
Saved data/raw/CF/000132440418000011.htm
Saved data/raw/CF/000110465918009851.htm
Saved data/raw/CF/000132440418000003.htm
Saved data/raw/CF/000110465917065253.htm
Saved data/raw/CF/000132440417000023.htm
Saved data/raw/CF/000110465917048949.htm
Saved data/raw/CF/000132440417000017.htm
Saved data/raw/CF/000110465917029481.htm
Saved data/raw/CF/000132440417000011.htm
Saved data/raw/CF/000110465917009688.htm
Saved data/raw/CF/000132440417000004.htm
Saved data/raw/CF/000110465916154261.htm
Saved data/raw/CF/000132440416000038.htm
Saved data/raw/CF/000110465916136656.htm
Saved data/raw/CF/000132440416000033.htm
Saved data/raw/CF/000110465916117776.htm
Saved data/raw/CF/000132440416000027.htm
Saved data/raw/CF/000110465916097770.htm
Saved data/raw/CF/000110465916097760.htm
Saved data/raw/CF/000110465915075848.htm
Saved data/raw/CF/000110465915075839.htm
Saved data/raw/CF/000110465915056609.htm
Saved data/raw/CF/000132440415000004.htm
Saved data/raw/CF/000110465915034981.htm
Saved data/raw/CF/000162828015003829.htm