In [1]:
import pandas as pd
import os
from bs4 import BeautifulSoup
import pyarrow

In [2]:
def clean_filing(path):
    with open(path,"r",encoding="utf-8") as f:
        html=f.read()
    soup= BeautifulSoup(html,"lxml")
    tables= soup.find_all("table")
    for table in tables:
        table.decompose()
    text_after= soup.get_text(separator=" ")
    eliminate_point=text_after.lower().find("forward-looking statements")
    if eliminate_point==-1:
        body = text_after
        print("Warning: phase not found, kept full text")
    else:
        body=text_after[:eliminate_point]

    return body

In [4]:
records=[]
for ticker in os.listdir("data/raw"):
    print(ticker)
    ticket_folder=f"data/raw/{ticker}"
    for file_name in os.listdir(ticket_folder):
        file_path=f"{ticket_folder}\{file_name}"
        body=clean_filing(file_path)
        print(ticker, file_name, len(body))
        accession=file_name.replace(".htm","")
        records.append({"ticker":ticker,"accession":accession,"text":body})

filings=pd.DataFrame(records)
print(filings.head())

AAPL
AAPL 000032019317000006.htm 1933
AAPL 000032019317000067.htm 2125
AAPL 000032019318000005.htm 2153
AAPL 000032019318000067.htm 2801
AAPL 000032019318000098.htm 1867
AAPL 000032019318000142.htm 2994
AAPL 000032019319000002.htm 8655
AAPL 000032019319000007.htm 2926
AAPL 000032019319000063.htm 2842
AAPL 000032019319000073.htm 2401
AAPL 000032019319000117.htm 2421
AAPL 000032019320000008.htm 2520
AAPL 000032019320000050.htm 2999
AAPL 000032019320000060.htm 2866
AAPL 000032019320000094.htm 2704
AAPL 000032019321000009.htm 2559
AAPL 000032019321000055.htm 2822
AAPL 000032019321000063.htm 2372
AAPL 000032019321000104.htm 2532
AAPL 000032019322000006.htm 2341
AAPL 000032019322000058.htm 2531
AAPL 000032019322000069.htm 2368
AAPL 000032019322000107.htm 2796
AAPL 000032019323000005.htm 2265
AAPL 000032019323000063.htm 2381
AAPL 000032019323000075.htm 2212
AAPL 000032019323000104.htm 2202
AAPL 000032019324000005.htm 2497
AAPL 000032019324000067.htm 2555
AAPL 000032019324000080.htm 2408
AAPL 000032019324000120.htm 2677
AAPL 000032019325000007.htm 2230
AAPL 000032019325000055.htm 2275
AAPL 000032019325000071.htm 2109
AAPL 000032019325000077.htm 2763
AAPL 000032019326000005.htm 2314
AAPL 000032019326000011.htm 2562
AAPL 000032019326000018.htm 2227
AAPL 000119312515354756.htm 2455
AAPL 000119312516438421.htm 2284
AAPL 000119312516556520.htm 2998
AAPL 000162828016017762.htm 2064
AAPL 000162828016020258.htm 1998
AAPL 000162828017000663.htm 2078
AAPL 000162828017004663.htm 3141
AMZN
AMZN 000101872420000028.htm 29031
AMZN 000101872421000002.htm 29460
AMZN 000101872421000008.htm 35672
AMZN 000101872421000018.htm 28142
AMZN 000101872421000026.htm 32275
AMZN 000101872422000002.htm 35922
AMZN 000101872422000011.htm 31022
AMZN 000101872422000017.htm 35616
AMZN 000101872422000021.htm 19115
AMZN 000101872423000002.htm 21452
AMZN 000101872423000006.htm 22160
AMZN 000101872423000010.htm 22047
AMZN 000101872423000016.htm 24612
AMZN 000101872424000006.htm 31401
AMZN 000101872424000081.htm 29731
AMZN 000101872424000128.htm 6484
AMZN 000101872424000158.htm 7660
AMZN 000101872425000002.htm 9691
AMZN 000101872425000034.htm 7615
AMZN 000101872425000084.htm 7708
AMZN 000101872425000121.htm 11096
AMZN 000101872426000002.htm 13432
AMZN 000101872426000012.htm 14230
AMZN 000101872426000024.htm 14270
CF
Warning: phase not found, kept full text
CF 000110465915034981.htm 626
Warning: phase not found, kept full text
CF 000110465915056609.htm 590
CF 000110465915075839.htm 28703
CF 000110465915075848.htm 359
CF 000110465916097760.htm 28732
CF 000110465916097770.htm 2188
CF 000110465916117776.htm 2804
CF 000110465916136656.htm 2933
CF 000110465916154261.htm 653
CF 000110465917009688.htm 376
CF 000110465917029481.htm 356
CF 000110465917048949.htm 360
CF 000110465917065253.htm 430
CF 000110465918009851.htm 445
CF 000110465918029887.htm 415
CF 000110465918048811.htm 417
CF 000110465918065148.htm 424
CF 000110465919007986.htm 424
CF 000110465919026136.htm 418
CF 000110465919043009.htm 420
Warning: phase not found, kept full text
CF 000110465919057897.htm 30122
Warning: phase not found, kept full text
CF 000110465920019476.htm 31987
Warning: phase not found, kept full text
CF 000110465920057641.htm 27939
Warning: phase not found, kept full text
CF 000110465920090923.htm 30206
Warning: phase not found, kept full text
CF 000110465920121424.htm 478
Warning: phase not found, kept full text
CF 000110465921024963.htm 30585
Warning: phase not found, kept full text
CF 000110465921061883.htm 30133
Warning: phase not found, kept full text
CF 000110465921102325.htm 24193
Warning: phase not found, kept full text
CF 000110465921133868.htm 29798
Warning: phase not found, kept full text
CF 000110465922024015.htm 71
Warning: phase not found, kept full text
CF 000110465922055931.htm 32811
Warning: phase not found, kept full text
CF 000110465922084736.htm 33705
Warning: phase not found, kept full text
CF 000110465923022431.htm 75
Warning: phase not found, kept full text
CF 000110465923054477.htm 37516
Warning: phase not found, kept full text
CF 000110465923086877.htm 35868
Warning: phase not found, kept full text
CF 000110465923113430.htm 36514
Warning: phase not found, kept full text
CF 000110465924024069.htm 75
Warning: phase not found, kept full text
CF 000110465924055837.htm 36459
Warning: phase not found, kept full text
CF 000110465924086801.htm 22336
Warning: phase not found, kept full text
CF 000110465924112673.htm 22658
Warning: phase not found, kept full text
CF 000110465925015219.htm 25263
Warning: phase not found, kept full text
CF 000110465925045606.htm 26427
Warning: phase not found, kept full text
CF 000110465925074767.htm 29181
Warning: phase not found, kept full text
CF 000110465925107103.htm 120
Warning: phase not found, kept full text
CF 000110465926017110.htm 32631
Warning: phase not found, kept full text
CF 000110465926056338.htm 72
Warning: phase not found, kept full text
CF 000110465926091275.htm 31571
CF 000132440415000004.htm 17976
CF 000132440416000027.htm 11111
CF 000132440416000033.htm 15111
CF 000132440416000038.htm 18872
CF 000132440417000004.htm 19169
CF 000132440417000011.htm 16229
CF 000132440417000017.htm 17523
CF 000132440417000023.htm 17339
CF 000132440418000003.htm 20891
CF 000132440418000011.htm 14453
CF 000132440418000017.htm 16810
CF 000132440418000024.htm 17609
CF 000132440419000003.htm 15172
CF 000132440419000009.htm 13877
CF 000132440419000016.htm 14924
CF 000132440419000021.htm 14710
CF 000132440420000002.htm 14378
CF 000132440420000010.htm 14812
CF 000132440420000017.htm 25135
CF 000132440420000023.htm 24817
CF 000132440421000004.htm 26983
CF 000132440421000011.htm 23423
CF 000132440421000020.htm 28543
CF 000132440421000030.htm 33281
CF 000132440422000004.htm 29313
CF 000132440422000014.htm 28943
CF 000132440422000020.htm 27842
CF 000132440422000026.htm 27431
CF 000132440423000003.htm 30134
CF 000132440423000010.htm 27322
CF 000132440423000017.htm 27611
CF 000132440423000022.htm 28364
CF 000132440424000003.htm 28865
CF 000132440424000012.htm 26972
CF 000132440424000018.htm 27145
CF 000132440424000024.htm 26059
CF 000132440425000004.htm 26060
CF 000132440425000013.htm 28296
CF 000132440425000022.htm 27687
CF 000132440425000028.htm 28843
CF 000132440426000003.htm 29114
CF 000132440426000011.htm 27814
CF 000132440426000017.htm 29611
CF 000162828015003829.htm 20418
COST
COST 000090983222000029.htm 1957
COST 000090983223000010.htm 2548
COST 000090983223000025.htm 2072
COST 000090983223000038.htm 1829
COST 000090983223000062.htm 2576
COST 000090983224000012.htm 2846
COST 000090983224000026.htm 2229
COST 000090983224000043.htm 2214
COST 000090983224000075.htm 1707
COST 000090983225000012.htm 2493
COST 000090983225000031.htm 1761
COST 000090983225000093.htm 1917
COST 000090983225000164.htm 1659
COST 000090983226000025.htm 2476
COST 000090983226000046.htm 1778
COST 000090983226000084.htm 1979
COST 000119312516787613.htm 1637
COST 000119312517069544.htm 3253
COST 000119312517184018.htm 2093
COST 000119312517304742.htm 2754
COST 000119312517369704.htm 2117
COST 000119312518073668.htm 3113
COST 000119312518180670.htm 1880
COST 000119312518293414.htm 3712
COST 000119312518348921.htm 2001
COST 000119312519067406.htm 2493
COST 000119312519161475.htm 1814
COST 000119312519261698.htm 2330
COST 000119312519312824.htm 1827
COST 000119312520063247.htm 2701
COST 000119312520154276.htm 1928
COST 000119312520253502.htm 2299
COST 000119312520314970.htm 1944
COST 000119312521069673.htm 2309
COST 000119312521175491.htm 1902
COST 000119312521280728.htm 2283
COST 000119312521352764.htm 1792
COST 000119312522065629.htm 2538
COST 000119312522161034.htm 1984
COST 000119312522249988.htm 1827
GOOGL
GOOGL 000165204423000067.htm 7045
GOOGL 000165204423000088.htm 4808
GOOGL 000165204424000014.htm 4546
GOOGL 000165204424000047.htm 5174
GOOGL 000165204424000076.htm 3664
GOOGL 000165204424000115.htm 4846
GOOGL 000165204425000010.htm 4526
GOOGL 000165204425000040.htm 5434
GOOGL 000165204425000056.htm 4318
GOOGL 000165204425000087.htm 5510
GOOGL 000165204426000012.htm 5079
GOOGL 000165204426000043.htm 4881
GOOGL 000165204426000066.htm 5940
MSFT
MSFT 000095017023034400.htm 9091
MSFT 000095017023054848.htm 6120
MSFT 000095017024008809.htm 7867
MSFT 000095017024048268.htm 5855
MSFT 000095017024087835.htm 8275
MSFT 000095017024118955.htm 6158
MSFT 000095017025010484.htm 5965
MSFT 000095017025061032.htm 6188
MSFT 000095017025100226.htm 6309
MSFT 000119312520278410.htm 5231
MSFT 000119312521017683.htm 5321
MSFT 000119312521134213.htm 7384
MSFT 000119312521225746.htm 7681
MSFT 000119312521307941.htm 6395
MSFT 000119312522017041.htm 4881
MSFT 000119312522120207.htm 7112
MSFT 000119312522202034.htm 8026
MSFT 000119312522268356.htm 6545
MSFT 000119312523014230.htm 6432
MSFT 000119312523115280.htm 4949
MSFT 000119312525256310.htm 7473
MSFT 000119312526027198.htm 7614
MSFT 000119312526191457.htm 7435
MSFT 000119312526323632.htm 9447
T
T 000073271722000080.htm 17396
T 000073271722000099.htm 15485
T 000073271723000007.htm 20253
T 000073271723000019.htm 13763
T 000073271723000043.htm 15556
T 000073271723000054.htm 15847
T 000073271724000006.htm 17436
T 000073271724000018.htm 11445
T 000073271724000050.htm 11795
Warning: phase not found, kept full text
T 000073271724000056.htm 1243
T 000073271725000007.htm 17292
T 000073271725000020.htm 12526
Warning: phase not found, kept full text
T 000073271725000076.htm 1207
T 000073271725000163.htm 16545
T 000073271726000047.htm 25680
T 000073271726000203.htm 15530
T 000073271726000294.htm 15825
TSLA
Warning: phase not found, kept full text
TSLA 000095017021000423.htm 1065
Warning: phase not found, kept full text
TSLA 000095017023031241.htm 1703
TSLA 000095017023033544.htm 28863
Warning: phase not found, kept full text
TSLA 000095017023050938.htm 1912
Warning: phase not found, kept full text
TSLA 000095017024000282.htm 2014
TSLA 000095017024007073.htm 33508
Warning: phase not found, kept full text
TSLA 000095017024040274.htm 2168
TSLA 000095017024046895.htm 30746
TSLA 000156459018016465.htm 3406
TSLA 000156459018018490.htm 14536
Warning: phase not found, kept full text
TSLA 000156459018023716.htm 490
TSLA 000156459018023815.htm 3649
TSLA 000156459018024902.htm 9788
TSLA 000156459019000013.htm 3995
TSLA 000156459019000740.htm 4686
TSLA 000156459019001399.htm 16680
TSLA 000156459019010743.htm 3167
TSLA 000156459019012758.htm 10745
TSLA 000156459019024414.htm 1908
TSLA 000156459019025855.htm 8466
Warning: phase not found, kept full text
TSLA 000156459019036274.htm 1346
TSLA 000156459019037581.htm 25838
Warning: phase not found, kept full text
TSLA 000156459020000161.htm 1682
TSLA 000156459020002489.htm 28045
Warning: phase not found, kept full text
TSLA 000156459020014992.htm 1188
TSLA 000156459020019776.htm 28064
Warning: phase not found, kept full text
TSLA 000156459020031568.htm 1064
TSLA 000156459020033069.htm 27349
Warning: phase not found, kept full text
TSLA 000156459020045592.htm 1052
TSLA 000156459020047108.htm 29096
TSLA 000156459021000008.htm 1156
TSLA 000156459021002645.htm 16229
TSLA 000156459021017443.htm 1265
TSLA 000156459021020558.htm 15520
TSLA 000156459021037953.htm 15532
Warning: phase not found, kept full text
TSLA 000156459021049874.htm 1106
TSLA 000156459021051307.htm 15556
Warning: phase not found, kept full text
TSLA 000156459022000009.htm 1191
TSLA 000156459022002476.htm 16194
Warning: phase not found, kept full text
TSLA 000156459022013264.htm 1824
TSLA 000156459022014917.htm 15451
Warning: phase not found, kept full text
TSLA 000156459022025153.htm 1890
TSLA 000156459022026048.htm 15194
TSLA 000156459022033053.htm 2301
TSLA 000156459022034639.htm 9163
TSLA 000156459023000002.htm 2327
TSLA 000156459023000799.htm 10026
Warning: phase not found, kept full text
TSLA 000156459023005126.htm 1877
TSLA 000156459023005959.htm 9026
TSLA 000162828023034588.htm 30110
Warning: phase not found, kept full text
TSLA 000162828024030714.htm 1852
Warning: phase not found, kept full text
TSLA 000162828024041816.htm 1755
Warning: phase not found, kept full text
TSLA 000162828025000007.htm 1994
TSLA 000162828025002993.htm 40401
Warning: phase not found, kept full text
TSLA 000162828025016070.htm 2050
Warning: phase not found, kept full text
TSLA 000162828025033842.htm 1867
TSLA 000162828025035738.htm 36135
Warning: phase not found, kept full text
TSLA 000162828025043530.htm 1924
TSLA 000162828025045861.htm 36014
Warning: phase not found, kept full text
TSLA 000162828026000016.htm 1966
TSLA 000162828026003837.htm 47389
Warning: phase not found, kept full text
TSLA 000162828026022956.htm 1872
TSLA 000162828026026551.htm 37223
Warning: phase not found, kept full text
TSLA 000162828026046717.htm 1874
TSLA 000162828026049213.htm 39001
Warning: phase not found, kept full text
TSLA 000162828026064366.htm 1969
UNH
UNH 000073176621000018.htm 8814
UNH 000073176621000033.htm 8926
UNH 000073176621000040.htm 8168
UNH 000073176622000004.htm 8144
UNH 000073176622000016.htm 7287
UNH 000073176622000033.htm 6944
UNH 000073176622000041.htm 7173
UNH 000073176623000003.htm 6889
UNH 000073176623000026.htm 7272
UNH 000073176623000049.htm 7359
UNH 000073176623000058.htm 7655
UNH 000073176624000023.htm 7473
UNH 000073176624000146.htm 12367
UNH 000073176624000242.htm 10372
UNH 000073176624000320.htm 8428
UNH 000073176625000022.htm 8266
UNH 000073176625000123.htm 7817
UNH 000073176625000228.htm 14378
UNH 000073176625000301.htm 8800
  ticker           accession  \
0   AAPL  000032019317000006
1   AAPL  000032019317000067
2   AAPL  000032019318000005
3   AAPL  000032019318000067
4   AAPL  000032019318000098

                                                text
0  \n EX-99.1\n 2\n a8-kexhibit991q32017712017.ht...
1  \n EX-99.1\n 2\n a8-kexhibit991q420179302017.h...
2  \n EX-99.1\n 2\n a8-kexhibit991q12018123020.ht...
3  \n EX-99.1\n 2\n a8-kexhibit991q220183312018.h...
4  \n EX-99.1\n 2\n a8-kexhibit991q320186302018.h...

In [5]:
filings["length"] = filings["text"].str.len()
filings.groupby("ticker")["length"].describe()

,count,mean,std,min,25%,50%,75%,max
ticker,,,,,,,,
AAPL,45.0,2604.955556,974.349829,1867.0,2230.00,2421.0,2763.00,8655.0
AMZN,24.0,21660.166667,10168.771007,6484.0,12848.00,22103.5,30053.75,35922.0
CF,91.0,18877.571429,12326.270603,71.0,2868.50,23423.0,28787.50,37516.0
COST,40.0,2214.300000,465.783773,1637.0,1867.25,2082.5,2493.00,3712.0
GOOGL,13.0,5059.307692,829.679897,3664.0,4546.00,4881.0,5434.00,7045.0
MSFT,24.0,6823.083333,1233.515299,4881.0,6081.25,6488.5,7630.75,9447.0
T,17.0,14401.411765,5953.814240,1207.0,12526.00,15556.0,17292.00,25680.0
TSLA,66.0,11612.772727,13040.409482,490.0,1872.50,3527.5,16220.25,47389.0
UNH,19.0,8554.315789,1928.063768,6889.0,7323.00,8144.0,8807.00,14378.0

In [6]:
filings

,ticker,accession,text,length
0,AAPL,000032019317000006,\n EX-99.1\n 2\n a8-kexhibit991q32017712017.ht...,1933
1,AAPL,000032019317000067,\n EX-99.1\n 2\n a8-kexhibit991q420179302017.h...,2125
2,AAPL,000032019318000005,\n EX-99.1\n 2\n a8-kexhibit991q12018123020.ht...,2153
3,AAPL,000032019318000067,\n EX-99.1\n 2\n a8-kexhibit991q220183312018.h...,2801
4,AAPL,000032019318000098,\n EX-99.1\n 2\n a8-kexhibit991q320186302018.h...,1867
...,...,...,...,...
334,UNH,000073176624000320,\n EX-99.1\n 2\n a2024q3exhibit991.htm\n EX-99...,8428
335,UNH,000073176625000022,\n EX-99.1\n 2\n a2024q4exhibit991.htm\n EX-99...,8266
336,UNH,000073176625000123,\n EX-99.1\n 2\n a2025q1exhibit991.htm\n EX-99...,7817
337,UNH,000073176625000228,\n EX-99.1\n 2\n a2025q2exhibit991.htm\n EX-99...,14378
338,UNH,000073176625000301,\n EX-99.1\n 2\n a2025q3exhibit991.htm\n EX-99...,8800

In [7]:
os.makedirs("data/processed/", exist_ok=True)
filings.to_csv("data/processed/filings.csv",index=False)